### PR TITLE
Pin `OpenSSL_jll` to version 1

### PR DESCRIPTION
**Pull request by MichaelHatherly**
The newest release, version 3, is not compatible with the binary artifacts shipped with this package.

Also add some testing to this package to make sure the fix is successful. Test against Julia version 1.8 and 1.9 for now.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
We also need to go back in the PumasRegistry and retro-cap old versions of LicenseSpring_jll.

**Comment by MichaelHatherly** [comment]
Ah, hold on, should we actually be adjusting https://github.com/PumasAI/LicenseSpringBuilder instead? This is *all* meant to be auto-generated content from there I would assume?

**Comment by DilumAluthge** [comment]
> Ah, hold on, should we actually be adjusting https://github.com/PumasAI/LicenseSpringBuilder instead? This is _all_ meant to be auto-generated content from there I would assume?

Hmmm. Let's ask @aviks

**Comment by aviks** [comment]
Ah, I had to look at the code, but yes, this package here is auto-generated from `LicenseSpringBuilder.jll`. That builder simply repackages the binaries from the vendor, hence the issue with OpenSSL versions. We do not have access to their sources (without an enterprise license) . They may have newer binaries with updated depdencies.

**Comment by MichaelHatherly** [comment]
Right, so we'll need to update the compat over in the builder repo. I'll close this one then. @aviks is the process pretty simple for doing that generation? I've never tried it.

**Comment by aviks** [comment]
The command to run is mentioned in the readme. You'll need BinaryBuilder in the default environment I guess. You'll also need a `GITHUB_TOKEN` env variable for the script to be able to write to github. 

I vaguely remember there may be some complication with version numbers -- but maybe not :)

**Pull request closed without merging**
